# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C5yg8ldhml6vt9wa2i9WWEt7iNlymOpm
"""

import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Height_Weight_single_variable_data_101_series_1.0.csv")

df



reg = linear_model.LinearRegression()
reg

df.plot(x='Height', y='Weight', figsize=(12,8))

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('Height(cm)')
plt.ylabel('Weight(kg)')
plt.scatter(df.Height,df.Weight, color = 'red', marker='*')

reg = linear_model.LinearRegression()
reg.fit(df[['Height']], df.Weight)

reg.predict(np.array([180]).reshape(-1, 1))

reg.coef_

reg.intercept_

#y=m*x+b
0.96001838*180-95.6624846143313

